apiVersion: v1
kind: Pod
metadata:
  name: nffplay
spec:
  containers:
    - name: nffplay
      image: 'dev/nff-go-playground'
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - mountPath: /sys/bus/pci/drivers
          name: drivers
        - mountPath: /sys/kernel/mm/hugepages
          name: hugepage
        - mountPath: /sys/devices/system/node
          name: node
        - mountPath: /dev
          name: dev
      resources:
        limits:
          hugepages-2Mi: 100Mi
          memory: 100Mi
        requests:
          memory: 100Mi
      command: ["sleep", "infinity"]
  volumes:
    - name: drivers
      hostPath:
        path: /sys/bus/pci/drivers
    - name: hugepage
      hostPath:
        path: /sys/kernel/mm/hugepages
    - name: node
      hostPath:
        path: /sys/devices/system/node
    - name: dev
      hostPath:
        path: /dev
  securityContext:
    runAsUser: 0
  restartPolicy: Never
